server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/marca/**
        - id: MS-Autorizacion
          uri: lb://MS-Autorizacion
          predicates:
            - Path=/autorizacion/**
        - id: ms-marcas
          uri: lb://ms-marcas
          predicates:
            - Path=/marcas/**